// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('queueApp').controller('UserCtrl', function($scope) {
  return $scope.guests = [
    {
      name: 'Rob'
    }, {
      name: 'Danielle'
    }
  ];
});
